@host = http://localhost:3000




###get

GET {{host}}/student HTTP/1.1
Content-Type: application/json
User-Agent: vscode-request

### post

POST {{host}}/student HTTP/1.1
Content-Type:application/json
User-Agent: vscode-request

{
 "name":"xyz",
 "age":18,
 "grade":1,
 "class_id":1
}

###put

PUT {{host}}/student/13 HTTP/1.1
Content-Type:application/json
User-Agent: vscode-request

{
 "name":"567",
 "age":18,
 "grade":1
}


### delete

DELETE {{host}}/student/14 HTTP/1.1
Content-Type:application/json
User-Agent: vscode-request



